/* soapH.h
   Generated by gSOAP 2.8.12 from CAGAccessService.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACHistoryVersionResponse
#define SOAP_TYPE__ns1__downloadCACHistoryVersionResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACHistoryVersionResponse(struct soap*, const char*, int, const _ns1__downloadCACHistoryVersionResponse *, const char*);
SOAP_FMAC3 _ns1__downloadCACHistoryVersionResponse * SOAP_FMAC4 soap_in__ns1__downloadCACHistoryVersionResponse(struct soap*, const char*, _ns1__downloadCACHistoryVersionResponse *, const char*);

#ifndef soap_write__ns1__downloadCACHistoryVersionResponse
#define soap_write__ns1__downloadCACHistoryVersionResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACHistoryVersionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACHistoryVersionResponse * SOAP_FMAC4 soap_get__ns1__downloadCACHistoryVersionResponse(struct soap*, _ns1__downloadCACHistoryVersionResponse *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACHistoryVersionResponse
#define soap_read__ns1__downloadCACHistoryVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACHistoryVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACHistoryVersionResponse * SOAP_FMAC2 soap_instantiate__ns1__downloadCACHistoryVersionResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACHistoryVersionResponse * soap_new__ns1__downloadCACHistoryVersionResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACHistoryVersionResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACHistoryVersionResponse * soap_new_req__ns1__downloadCACHistoryVersionResponse(struct soap *soap, std::string *out) { _ns1__downloadCACHistoryVersionResponse *_p = soap_instantiate__ns1__downloadCACHistoryVersionResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACHistoryVersionResponse::out = out; return _p; }

inline _ns1__downloadCACHistoryVersionResponse * soap_new_set__ns1__downloadCACHistoryVersionResponse(struct soap *soap, std::string *out) { _ns1__downloadCACHistoryVersionResponse *_p = soap_instantiate__ns1__downloadCACHistoryVersionResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACHistoryVersionResponse::out = out; return _p; }

inline void soap_delete__ns1__downloadCACHistoryVersionResponse(struct soap *soap, _ns1__downloadCACHistoryVersionResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACHistoryVersionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACHistoryVersion
#define SOAP_TYPE__ns1__downloadCACHistoryVersion (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACHistoryVersion(struct soap*, const char*, int, const _ns1__downloadCACHistoryVersion *, const char*);
SOAP_FMAC3 _ns1__downloadCACHistoryVersion * SOAP_FMAC4 soap_in__ns1__downloadCACHistoryVersion(struct soap*, const char*, _ns1__downloadCACHistoryVersion *, const char*);

#ifndef soap_write__ns1__downloadCACHistoryVersion
#define soap_write__ns1__downloadCACHistoryVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACHistoryVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACHistoryVersion * SOAP_FMAC4 soap_get__ns1__downloadCACHistoryVersion(struct soap*, _ns1__downloadCACHistoryVersion *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACHistoryVersion
#define soap_read__ns1__downloadCACHistoryVersion(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACHistoryVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACHistoryVersion * SOAP_FMAC2 soap_instantiate__ns1__downloadCACHistoryVersion(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACHistoryVersion * soap_new__ns1__downloadCACHistoryVersion(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACHistoryVersion(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACHistoryVersion * soap_new_req__ns1__downloadCACHistoryVersion(struct soap *soap, std::string *in0) { _ns1__downloadCACHistoryVersion *_p = soap_instantiate__ns1__downloadCACHistoryVersion(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACHistoryVersion::in0 = in0; return _p; }

inline _ns1__downloadCACHistoryVersion * soap_new_set__ns1__downloadCACHistoryVersion(struct soap *soap, std::string *in0) { _ns1__downloadCACHistoryVersion *_p = soap_instantiate__ns1__downloadCACHistoryVersion(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACHistoryVersion::in0 = in0; return _p; }

inline void soap_delete__ns1__downloadCACHistoryVersion(struct soap *soap, _ns1__downloadCACHistoryVersion *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACHistoryVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACConfigResponse
#define SOAP_TYPE__ns1__uploadCACConfigResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACConfigResponse(struct soap*, const char*, int, const _ns1__uploadCACConfigResponse *, const char*);
SOAP_FMAC3 _ns1__uploadCACConfigResponse * SOAP_FMAC4 soap_in__ns1__uploadCACConfigResponse(struct soap*, const char*, _ns1__uploadCACConfigResponse *, const char*);

#ifndef soap_write__ns1__uploadCACConfigResponse
#define soap_write__ns1__uploadCACConfigResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACConfigResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACConfigResponse * SOAP_FMAC4 soap_get__ns1__uploadCACConfigResponse(struct soap*, _ns1__uploadCACConfigResponse *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACConfigResponse
#define soap_read__ns1__uploadCACConfigResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACConfigResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACConfigResponse * SOAP_FMAC2 soap_instantiate__ns1__uploadCACConfigResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACConfigResponse * soap_new__ns1__uploadCACConfigResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACConfigResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACConfigResponse * soap_new_req__ns1__uploadCACConfigResponse(struct soap *soap, std::string *out) { _ns1__uploadCACConfigResponse *_p = soap_instantiate__ns1__uploadCACConfigResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACConfigResponse::out = out; return _p; }

inline _ns1__uploadCACConfigResponse * soap_new_set__ns1__uploadCACConfigResponse(struct soap *soap, std::string *out) { _ns1__uploadCACConfigResponse *_p = soap_instantiate__ns1__uploadCACConfigResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACConfigResponse::out = out; return _p; }

inline void soap_delete__ns1__uploadCACConfigResponse(struct soap *soap, _ns1__uploadCACConfigResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACConfigResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACConfig
#define SOAP_TYPE__ns1__uploadCACConfig (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACConfig(struct soap*, const char*, int, const _ns1__uploadCACConfig *, const char*);
SOAP_FMAC3 _ns1__uploadCACConfig * SOAP_FMAC4 soap_in__ns1__uploadCACConfig(struct soap*, const char*, _ns1__uploadCACConfig *, const char*);

#ifndef soap_write__ns1__uploadCACConfig
#define soap_write__ns1__uploadCACConfig(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACConfig", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACConfig * SOAP_FMAC4 soap_get__ns1__uploadCACConfig(struct soap*, _ns1__uploadCACConfig *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACConfig
#define soap_read__ns1__uploadCACConfig(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACConfig(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACConfig * SOAP_FMAC2 soap_instantiate__ns1__uploadCACConfig(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACConfig * soap_new__ns1__uploadCACConfig(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACConfig(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACConfig * soap_new_req__ns1__uploadCACConfig(struct soap *soap, std::string *in0) { _ns1__uploadCACConfig *_p = soap_instantiate__ns1__uploadCACConfig(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACConfig::in0 = in0; return _p; }

inline _ns1__uploadCACConfig * soap_new_set__ns1__uploadCACConfig(struct soap *soap, std::string *in0) { _ns1__uploadCACConfig *_p = soap_instantiate__ns1__uploadCACConfig(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACConfig::in0 = in0; return _p; }

inline void soap_delete__ns1__uploadCACConfig(struct soap *soap, _ns1__uploadCACConfig *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACConfig(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACHeartbeatInfoResponse
#define SOAP_TYPE__ns1__uploadCACHeartbeatInfoResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACHeartbeatInfoResponse(struct soap*, const char*, int, const _ns1__uploadCACHeartbeatInfoResponse *, const char*);
SOAP_FMAC3 _ns1__uploadCACHeartbeatInfoResponse * SOAP_FMAC4 soap_in__ns1__uploadCACHeartbeatInfoResponse(struct soap*, const char*, _ns1__uploadCACHeartbeatInfoResponse *, const char*);

#ifndef soap_write__ns1__uploadCACHeartbeatInfoResponse
#define soap_write__ns1__uploadCACHeartbeatInfoResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACHeartbeatInfoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACHeartbeatInfoResponse * SOAP_FMAC4 soap_get__ns1__uploadCACHeartbeatInfoResponse(struct soap*, _ns1__uploadCACHeartbeatInfoResponse *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACHeartbeatInfoResponse
#define soap_read__ns1__uploadCACHeartbeatInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACHeartbeatInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACHeartbeatInfoResponse * SOAP_FMAC2 soap_instantiate__ns1__uploadCACHeartbeatInfoResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACHeartbeatInfoResponse * soap_new__ns1__uploadCACHeartbeatInfoResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACHeartbeatInfoResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACHeartbeatInfoResponse * soap_new_req__ns1__uploadCACHeartbeatInfoResponse(struct soap *soap, std::string *out) { _ns1__uploadCACHeartbeatInfoResponse *_p = soap_instantiate__ns1__uploadCACHeartbeatInfoResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACHeartbeatInfoResponse::out = out; return _p; }

inline _ns1__uploadCACHeartbeatInfoResponse * soap_new_set__ns1__uploadCACHeartbeatInfoResponse(struct soap *soap, std::string *out) { _ns1__uploadCACHeartbeatInfoResponse *_p = soap_instantiate__ns1__uploadCACHeartbeatInfoResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACHeartbeatInfoResponse::out = out; return _p; }

inline void soap_delete__ns1__uploadCACHeartbeatInfoResponse(struct soap *soap, _ns1__uploadCACHeartbeatInfoResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACHeartbeatInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACHeartbeatInfo
#define SOAP_TYPE__ns1__uploadCACHeartbeatInfo (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACHeartbeatInfo(struct soap*, const char*, int, const _ns1__uploadCACHeartbeatInfo *, const char*);
SOAP_FMAC3 _ns1__uploadCACHeartbeatInfo * SOAP_FMAC4 soap_in__ns1__uploadCACHeartbeatInfo(struct soap*, const char*, _ns1__uploadCACHeartbeatInfo *, const char*);

#ifndef soap_write__ns1__uploadCACHeartbeatInfo
#define soap_write__ns1__uploadCACHeartbeatInfo(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACHeartbeatInfo * SOAP_FMAC4 soap_get__ns1__uploadCACHeartbeatInfo(struct soap*, _ns1__uploadCACHeartbeatInfo *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACHeartbeatInfo
#define soap_read__ns1__uploadCACHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACHeartbeatInfo * SOAP_FMAC2 soap_instantiate__ns1__uploadCACHeartbeatInfo(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACHeartbeatInfo * soap_new__ns1__uploadCACHeartbeatInfo(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACHeartbeatInfo(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACHeartbeatInfo * soap_new_req__ns1__uploadCACHeartbeatInfo(struct soap *soap, std::string *in0) { _ns1__uploadCACHeartbeatInfo *_p = soap_instantiate__ns1__uploadCACHeartbeatInfo(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACHeartbeatInfo::in0 = in0; return _p; }

inline _ns1__uploadCACHeartbeatInfo * soap_new_set__ns1__uploadCACHeartbeatInfo(struct soap *soap, std::string *in0) { _ns1__uploadCACHeartbeatInfo *_p = soap_instantiate__ns1__uploadCACHeartbeatInfo(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACHeartbeatInfo::in0 = in0; return _p; }

inline void soap_delete__ns1__uploadCACHeartbeatInfo(struct soap *soap, _ns1__uploadCACHeartbeatInfo *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACHeartbeatInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACLatestVersionResponse
#define SOAP_TYPE__ns1__downloadCACLatestVersionResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACLatestVersionResponse(struct soap*, const char*, int, const _ns1__downloadCACLatestVersionResponse *, const char*);
SOAP_FMAC3 _ns1__downloadCACLatestVersionResponse * SOAP_FMAC4 soap_in__ns1__downloadCACLatestVersionResponse(struct soap*, const char*, _ns1__downloadCACLatestVersionResponse *, const char*);

#ifndef soap_write__ns1__downloadCACLatestVersionResponse
#define soap_write__ns1__downloadCACLatestVersionResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACLatestVersionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACLatestVersionResponse * SOAP_FMAC4 soap_get__ns1__downloadCACLatestVersionResponse(struct soap*, _ns1__downloadCACLatestVersionResponse *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACLatestVersionResponse
#define soap_read__ns1__downloadCACLatestVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACLatestVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACLatestVersionResponse * SOAP_FMAC2 soap_instantiate__ns1__downloadCACLatestVersionResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACLatestVersionResponse * soap_new__ns1__downloadCACLatestVersionResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACLatestVersionResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACLatestVersionResponse * soap_new_req__ns1__downloadCACLatestVersionResponse(struct soap *soap, std::string *out) { _ns1__downloadCACLatestVersionResponse *_p = soap_instantiate__ns1__downloadCACLatestVersionResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACLatestVersionResponse::out = out; return _p; }

inline _ns1__downloadCACLatestVersionResponse * soap_new_set__ns1__downloadCACLatestVersionResponse(struct soap *soap, std::string *out) { _ns1__downloadCACLatestVersionResponse *_p = soap_instantiate__ns1__downloadCACLatestVersionResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACLatestVersionResponse::out = out; return _p; }

inline void soap_delete__ns1__downloadCACLatestVersionResponse(struct soap *soap, _ns1__downloadCACLatestVersionResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACLatestVersionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACLatestVersion
#define SOAP_TYPE__ns1__downloadCACLatestVersion (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACLatestVersion(struct soap*, const char*, int, const _ns1__downloadCACLatestVersion *, const char*);
SOAP_FMAC3 _ns1__downloadCACLatestVersion * SOAP_FMAC4 soap_in__ns1__downloadCACLatestVersion(struct soap*, const char*, _ns1__downloadCACLatestVersion *, const char*);

#ifndef soap_write__ns1__downloadCACLatestVersion
#define soap_write__ns1__downloadCACLatestVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACLatestVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACLatestVersion * SOAP_FMAC4 soap_get__ns1__downloadCACLatestVersion(struct soap*, _ns1__downloadCACLatestVersion *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACLatestVersion
#define soap_read__ns1__downloadCACLatestVersion(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACLatestVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACLatestVersion * SOAP_FMAC2 soap_instantiate__ns1__downloadCACLatestVersion(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACLatestVersion * soap_new__ns1__downloadCACLatestVersion(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACLatestVersion(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACLatestVersion * soap_new_req__ns1__downloadCACLatestVersion(struct soap *soap, std::string *in0) { _ns1__downloadCACLatestVersion *_p = soap_instantiate__ns1__downloadCACLatestVersion(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACLatestVersion::in0 = in0; return _p; }

inline _ns1__downloadCACLatestVersion * soap_new_set__ns1__downloadCACLatestVersion(struct soap *soap, std::string *in0) { _ns1__downloadCACLatestVersion *_p = soap_instantiate__ns1__downloadCACLatestVersion(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACLatestVersion::in0 = in0; return _p; }

inline void soap_delete__ns1__downloadCACLatestVersion(struct soap *soap, _ns1__downloadCACLatestVersion *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACLatestVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACUpdateFileResponse
#define SOAP_TYPE__ns1__downloadCACUpdateFileResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACUpdateFileResponse(struct soap*, const char*, int, const _ns1__downloadCACUpdateFileResponse *, const char*);
SOAP_FMAC3 _ns1__downloadCACUpdateFileResponse * SOAP_FMAC4 soap_in__ns1__downloadCACUpdateFileResponse(struct soap*, const char*, _ns1__downloadCACUpdateFileResponse *, const char*);

#ifndef soap_write__ns1__downloadCACUpdateFileResponse
#define soap_write__ns1__downloadCACUpdateFileResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACUpdateFileResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACUpdateFileResponse * SOAP_FMAC4 soap_get__ns1__downloadCACUpdateFileResponse(struct soap*, _ns1__downloadCACUpdateFileResponse *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACUpdateFileResponse
#define soap_read__ns1__downloadCACUpdateFileResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACUpdateFileResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACUpdateFileResponse * SOAP_FMAC2 soap_instantiate__ns1__downloadCACUpdateFileResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACUpdateFileResponse * soap_new__ns1__downloadCACUpdateFileResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACUpdateFileResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACUpdateFileResponse * soap_new_req__ns1__downloadCACUpdateFileResponse(struct soap *soap, std::string *out) { _ns1__downloadCACUpdateFileResponse *_p = soap_instantiate__ns1__downloadCACUpdateFileResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACUpdateFileResponse::out = out; return _p; }

inline _ns1__downloadCACUpdateFileResponse * soap_new_set__ns1__downloadCACUpdateFileResponse(struct soap *soap, std::string *out) { _ns1__downloadCACUpdateFileResponse *_p = soap_instantiate__ns1__downloadCACUpdateFileResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACUpdateFileResponse::out = out; return _p; }

inline void soap_delete__ns1__downloadCACUpdateFileResponse(struct soap *soap, _ns1__downloadCACUpdateFileResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACUpdateFileResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__downloadCACUpdateFile
#define SOAP_TYPE__ns1__downloadCACUpdateFile (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__downloadCACUpdateFile(struct soap*, const char*, int, const _ns1__downloadCACUpdateFile *, const char*);
SOAP_FMAC3 _ns1__downloadCACUpdateFile * SOAP_FMAC4 soap_in__ns1__downloadCACUpdateFile(struct soap*, const char*, _ns1__downloadCACUpdateFile *, const char*);

#ifndef soap_write__ns1__downloadCACUpdateFile
#define soap_write__ns1__downloadCACUpdateFile(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:downloadCACUpdateFile", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACUpdateFile * SOAP_FMAC4 soap_get__ns1__downloadCACUpdateFile(struct soap*, _ns1__downloadCACUpdateFile *, const char*, const char*);

#ifndef soap_read__ns1__downloadCACUpdateFile
#define soap_read__ns1__downloadCACUpdateFile(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__downloadCACUpdateFile(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__downloadCACUpdateFile * SOAP_FMAC2 soap_instantiate__ns1__downloadCACUpdateFile(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__downloadCACUpdateFile * soap_new__ns1__downloadCACUpdateFile(struct soap *soap, int n = -1) { return soap_instantiate__ns1__downloadCACUpdateFile(soap, n, NULL, NULL, NULL); }

inline _ns1__downloadCACUpdateFile * soap_new_req__ns1__downloadCACUpdateFile(struct soap *soap, std::string *in0) { _ns1__downloadCACUpdateFile *_p = soap_instantiate__ns1__downloadCACUpdateFile(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACUpdateFile::in0 = in0; return _p; }

inline _ns1__downloadCACUpdateFile * soap_new_set__ns1__downloadCACUpdateFile(struct soap *soap, std::string *in0) { _ns1__downloadCACUpdateFile *_p = soap_instantiate__ns1__downloadCACUpdateFile(soap, -1, NULL, NULL, NULL); _p->_ns1__downloadCACUpdateFile::in0 = in0; return _p; }

inline void soap_delete__ns1__downloadCACUpdateFile(struct soap *soap, _ns1__downloadCACUpdateFile *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__downloadCACUpdateFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACDataResponse
#define SOAP_TYPE__ns1__uploadCACDataResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACDataResponse(struct soap*, const char*, int, const _ns1__uploadCACDataResponse *, const char*);
SOAP_FMAC3 _ns1__uploadCACDataResponse * SOAP_FMAC4 soap_in__ns1__uploadCACDataResponse(struct soap*, const char*, _ns1__uploadCACDataResponse *, const char*);

#ifndef soap_write__ns1__uploadCACDataResponse
#define soap_write__ns1__uploadCACDataResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACDataResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACDataResponse * SOAP_FMAC4 soap_get__ns1__uploadCACDataResponse(struct soap*, _ns1__uploadCACDataResponse *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACDataResponse
#define soap_read__ns1__uploadCACDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACDataResponse * SOAP_FMAC2 soap_instantiate__ns1__uploadCACDataResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACDataResponse * soap_new__ns1__uploadCACDataResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACDataResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACDataResponse * soap_new_req__ns1__uploadCACDataResponse(struct soap *soap, std::string *out) { _ns1__uploadCACDataResponse *_p = soap_instantiate__ns1__uploadCACDataResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACDataResponse::out = out; return _p; }

inline _ns1__uploadCACDataResponse * soap_new_set__ns1__uploadCACDataResponse(struct soap *soap, std::string *out) { _ns1__uploadCACDataResponse *_p = soap_instantiate__ns1__uploadCACDataResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACDataResponse::out = out; return _p; }

inline void soap_delete__ns1__uploadCACDataResponse(struct soap *soap, _ns1__uploadCACDataResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCACData
#define SOAP_TYPE__ns1__uploadCACData (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCACData(struct soap*, const char*, int, const _ns1__uploadCACData *, const char*);
SOAP_FMAC3 _ns1__uploadCACData * SOAP_FMAC4 soap_in__ns1__uploadCACData(struct soap*, const char*, _ns1__uploadCACData *, const char*);

#ifndef soap_write__ns1__uploadCACData
#define soap_write__ns1__uploadCACData(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:uploadCACData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACData * SOAP_FMAC4 soap_get__ns1__uploadCACData(struct soap*, _ns1__uploadCACData *, const char*, const char*);

#ifndef soap_read__ns1__uploadCACData
#define soap_read__ns1__uploadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__uploadCACData * SOAP_FMAC2 soap_instantiate__ns1__uploadCACData(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__uploadCACData * soap_new__ns1__uploadCACData(struct soap *soap, int n = -1) { return soap_instantiate__ns1__uploadCACData(soap, n, NULL, NULL, NULL); }

inline _ns1__uploadCACData * soap_new_req__ns1__uploadCACData(struct soap *soap, std::string *in0) { _ns1__uploadCACData *_p = soap_instantiate__ns1__uploadCACData(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACData::in0 = in0; return _p; }

inline _ns1__uploadCACData * soap_new_set__ns1__uploadCACData(struct soap *soap, std::string *in0) { _ns1__uploadCACData *_p = soap_instantiate__ns1__uploadCACData(soap, -1, NULL, NULL, NULL); _p->_ns1__uploadCACData::in0 = in0; return _p; }

inline void soap_delete__ns1__uploadCACData(struct soap *soap, _ns1__uploadCACData *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCACData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); _p->SOAP_ENV__Text = SOAP_ENV__Text; return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); _p->__type = __type; _p->fault = fault; return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); _p->__any = __any; _p->__type = __type; _p->fault = fault; return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__downloadCACHistoryVersion
#define SOAP_TYPE___ns1__downloadCACHistoryVersion (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__downloadCACHistoryVersion(struct soap*, struct __ns1__downloadCACHistoryVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__downloadCACHistoryVersion(struct soap*, const struct __ns1__downloadCACHistoryVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__downloadCACHistoryVersion(struct soap*, const char*, int, const struct __ns1__downloadCACHistoryVersion *, const char*);
SOAP_FMAC3 struct __ns1__downloadCACHistoryVersion * SOAP_FMAC4 soap_in___ns1__downloadCACHistoryVersion(struct soap*, const char*, struct __ns1__downloadCACHistoryVersion *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__downloadCACHistoryVersion(struct soap*, const struct __ns1__downloadCACHistoryVersion *, const char*, const char*);

#ifndef soap_write___ns1__downloadCACHistoryVersion
#define soap_write___ns1__downloadCACHistoryVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__downloadCACHistoryVersion(soap, data, "-ns1:downloadCACHistoryVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__downloadCACHistoryVersion * SOAP_FMAC4 soap_get___ns1__downloadCACHistoryVersion(struct soap*, struct __ns1__downloadCACHistoryVersion *, const char*, const char*);

#ifndef soap_read___ns1__downloadCACHistoryVersion
#define soap_read___ns1__downloadCACHistoryVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__downloadCACHistoryVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__downloadCACHistoryVersion * SOAP_FMAC2 soap_instantiate___ns1__downloadCACHistoryVersion(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__downloadCACHistoryVersion * soap_new___ns1__downloadCACHistoryVersion(struct soap *soap, int n = -1) { return soap_instantiate___ns1__downloadCACHistoryVersion(soap, n, NULL, NULL, NULL); }

inline struct __ns1__downloadCACHistoryVersion * soap_new_req___ns1__downloadCACHistoryVersion(struct soap *soap) { struct __ns1__downloadCACHistoryVersion *_p = soap_instantiate___ns1__downloadCACHistoryVersion(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__downloadCACHistoryVersion * soap_new_set___ns1__downloadCACHistoryVersion(struct soap *soap, _ns1__downloadCACHistoryVersion *ns1__downloadCACHistoryVersion) { struct __ns1__downloadCACHistoryVersion *_p = soap_instantiate___ns1__downloadCACHistoryVersion(soap, -1, NULL, NULL, NULL); _p->ns1__downloadCACHistoryVersion = ns1__downloadCACHistoryVersion; return _p; }

inline void soap_delete___ns1__downloadCACHistoryVersion(struct soap *soap, struct __ns1__downloadCACHistoryVersion *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__downloadCACHistoryVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__uploadCACConfig
#define SOAP_TYPE___ns1__uploadCACConfig (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__uploadCACConfig(struct soap*, struct __ns1__uploadCACConfig *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__uploadCACConfig(struct soap*, const struct __ns1__uploadCACConfig *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__uploadCACConfig(struct soap*, const char*, int, const struct __ns1__uploadCACConfig *, const char*);
SOAP_FMAC3 struct __ns1__uploadCACConfig * SOAP_FMAC4 soap_in___ns1__uploadCACConfig(struct soap*, const char*, struct __ns1__uploadCACConfig *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__uploadCACConfig(struct soap*, const struct __ns1__uploadCACConfig *, const char*, const char*);

#ifndef soap_write___ns1__uploadCACConfig
#define soap_write___ns1__uploadCACConfig(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__uploadCACConfig(soap, data, "-ns1:uploadCACConfig", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__uploadCACConfig * SOAP_FMAC4 soap_get___ns1__uploadCACConfig(struct soap*, struct __ns1__uploadCACConfig *, const char*, const char*);

#ifndef soap_read___ns1__uploadCACConfig
#define soap_read___ns1__uploadCACConfig(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__uploadCACConfig(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__uploadCACConfig * SOAP_FMAC2 soap_instantiate___ns1__uploadCACConfig(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__uploadCACConfig * soap_new___ns1__uploadCACConfig(struct soap *soap, int n = -1) { return soap_instantiate___ns1__uploadCACConfig(soap, n, NULL, NULL, NULL); }

inline struct __ns1__uploadCACConfig * soap_new_req___ns1__uploadCACConfig(struct soap *soap) { struct __ns1__uploadCACConfig *_p = soap_instantiate___ns1__uploadCACConfig(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__uploadCACConfig * soap_new_set___ns1__uploadCACConfig(struct soap *soap, _ns1__uploadCACConfig *ns1__uploadCACConfig) { struct __ns1__uploadCACConfig *_p = soap_instantiate___ns1__uploadCACConfig(soap, -1, NULL, NULL, NULL); _p->ns1__uploadCACConfig = ns1__uploadCACConfig; return _p; }

inline void soap_delete___ns1__uploadCACConfig(struct soap *soap, struct __ns1__uploadCACConfig *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__uploadCACConfig(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__uploadCACHeartbeatInfo
#define SOAP_TYPE___ns1__uploadCACHeartbeatInfo (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__uploadCACHeartbeatInfo(struct soap*, struct __ns1__uploadCACHeartbeatInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__uploadCACHeartbeatInfo(struct soap*, const struct __ns1__uploadCACHeartbeatInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__uploadCACHeartbeatInfo(struct soap*, const char*, int, const struct __ns1__uploadCACHeartbeatInfo *, const char*);
SOAP_FMAC3 struct __ns1__uploadCACHeartbeatInfo * SOAP_FMAC4 soap_in___ns1__uploadCACHeartbeatInfo(struct soap*, const char*, struct __ns1__uploadCACHeartbeatInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__uploadCACHeartbeatInfo(struct soap*, const struct __ns1__uploadCACHeartbeatInfo *, const char*, const char*);

#ifndef soap_write___ns1__uploadCACHeartbeatInfo
#define soap_write___ns1__uploadCACHeartbeatInfo(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__uploadCACHeartbeatInfo(soap, data, "-ns1:uploadCACHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__uploadCACHeartbeatInfo * SOAP_FMAC4 soap_get___ns1__uploadCACHeartbeatInfo(struct soap*, struct __ns1__uploadCACHeartbeatInfo *, const char*, const char*);

#ifndef soap_read___ns1__uploadCACHeartbeatInfo
#define soap_read___ns1__uploadCACHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__uploadCACHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__uploadCACHeartbeatInfo * SOAP_FMAC2 soap_instantiate___ns1__uploadCACHeartbeatInfo(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__uploadCACHeartbeatInfo * soap_new___ns1__uploadCACHeartbeatInfo(struct soap *soap, int n = -1) { return soap_instantiate___ns1__uploadCACHeartbeatInfo(soap, n, NULL, NULL, NULL); }

inline struct __ns1__uploadCACHeartbeatInfo * soap_new_req___ns1__uploadCACHeartbeatInfo(struct soap *soap) { struct __ns1__uploadCACHeartbeatInfo *_p = soap_instantiate___ns1__uploadCACHeartbeatInfo(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__uploadCACHeartbeatInfo * soap_new_set___ns1__uploadCACHeartbeatInfo(struct soap *soap, _ns1__uploadCACHeartbeatInfo *ns1__uploadCACHeartbeatInfo) { struct __ns1__uploadCACHeartbeatInfo *_p = soap_instantiate___ns1__uploadCACHeartbeatInfo(soap, -1, NULL, NULL, NULL); _p->ns1__uploadCACHeartbeatInfo = ns1__uploadCACHeartbeatInfo; return _p; }

inline void soap_delete___ns1__uploadCACHeartbeatInfo(struct soap *soap, struct __ns1__uploadCACHeartbeatInfo *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__uploadCACHeartbeatInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__downloadCACLatestVersion
#define SOAP_TYPE___ns1__downloadCACLatestVersion (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__downloadCACLatestVersion(struct soap*, struct __ns1__downloadCACLatestVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__downloadCACLatestVersion(struct soap*, const struct __ns1__downloadCACLatestVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__downloadCACLatestVersion(struct soap*, const char*, int, const struct __ns1__downloadCACLatestVersion *, const char*);
SOAP_FMAC3 struct __ns1__downloadCACLatestVersion * SOAP_FMAC4 soap_in___ns1__downloadCACLatestVersion(struct soap*, const char*, struct __ns1__downloadCACLatestVersion *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__downloadCACLatestVersion(struct soap*, const struct __ns1__downloadCACLatestVersion *, const char*, const char*);

#ifndef soap_write___ns1__downloadCACLatestVersion
#define soap_write___ns1__downloadCACLatestVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__downloadCACLatestVersion(soap, data, "-ns1:downloadCACLatestVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__downloadCACLatestVersion * SOAP_FMAC4 soap_get___ns1__downloadCACLatestVersion(struct soap*, struct __ns1__downloadCACLatestVersion *, const char*, const char*);

#ifndef soap_read___ns1__downloadCACLatestVersion
#define soap_read___ns1__downloadCACLatestVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__downloadCACLatestVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__downloadCACLatestVersion * SOAP_FMAC2 soap_instantiate___ns1__downloadCACLatestVersion(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__downloadCACLatestVersion * soap_new___ns1__downloadCACLatestVersion(struct soap *soap, int n = -1) { return soap_instantiate___ns1__downloadCACLatestVersion(soap, n, NULL, NULL, NULL); }

inline struct __ns1__downloadCACLatestVersion * soap_new_req___ns1__downloadCACLatestVersion(struct soap *soap) { struct __ns1__downloadCACLatestVersion *_p = soap_instantiate___ns1__downloadCACLatestVersion(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__downloadCACLatestVersion * soap_new_set___ns1__downloadCACLatestVersion(struct soap *soap, _ns1__downloadCACLatestVersion *ns1__downloadCACLatestVersion) { struct __ns1__downloadCACLatestVersion *_p = soap_instantiate___ns1__downloadCACLatestVersion(soap, -1, NULL, NULL, NULL); _p->ns1__downloadCACLatestVersion = ns1__downloadCACLatestVersion; return _p; }

inline void soap_delete___ns1__downloadCACLatestVersion(struct soap *soap, struct __ns1__downloadCACLatestVersion *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__downloadCACLatestVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__downloadCACUpdateFile
#define SOAP_TYPE___ns1__downloadCACUpdateFile (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__downloadCACUpdateFile(struct soap*, struct __ns1__downloadCACUpdateFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__downloadCACUpdateFile(struct soap*, const struct __ns1__downloadCACUpdateFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__downloadCACUpdateFile(struct soap*, const char*, int, const struct __ns1__downloadCACUpdateFile *, const char*);
SOAP_FMAC3 struct __ns1__downloadCACUpdateFile * SOAP_FMAC4 soap_in___ns1__downloadCACUpdateFile(struct soap*, const char*, struct __ns1__downloadCACUpdateFile *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__downloadCACUpdateFile(struct soap*, const struct __ns1__downloadCACUpdateFile *, const char*, const char*);

#ifndef soap_write___ns1__downloadCACUpdateFile
#define soap_write___ns1__downloadCACUpdateFile(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__downloadCACUpdateFile(soap, data, "-ns1:downloadCACUpdateFile", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__downloadCACUpdateFile * SOAP_FMAC4 soap_get___ns1__downloadCACUpdateFile(struct soap*, struct __ns1__downloadCACUpdateFile *, const char*, const char*);

#ifndef soap_read___ns1__downloadCACUpdateFile
#define soap_read___ns1__downloadCACUpdateFile(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__downloadCACUpdateFile(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__downloadCACUpdateFile * SOAP_FMAC2 soap_instantiate___ns1__downloadCACUpdateFile(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__downloadCACUpdateFile * soap_new___ns1__downloadCACUpdateFile(struct soap *soap, int n = -1) { return soap_instantiate___ns1__downloadCACUpdateFile(soap, n, NULL, NULL, NULL); }

inline struct __ns1__downloadCACUpdateFile * soap_new_req___ns1__downloadCACUpdateFile(struct soap *soap) { struct __ns1__downloadCACUpdateFile *_p = soap_instantiate___ns1__downloadCACUpdateFile(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__downloadCACUpdateFile * soap_new_set___ns1__downloadCACUpdateFile(struct soap *soap, _ns1__downloadCACUpdateFile *ns1__downloadCACUpdateFile) { struct __ns1__downloadCACUpdateFile *_p = soap_instantiate___ns1__downloadCACUpdateFile(soap, -1, NULL, NULL, NULL); _p->ns1__downloadCACUpdateFile = ns1__downloadCACUpdateFile; return _p; }

inline void soap_delete___ns1__downloadCACUpdateFile(struct soap *soap, struct __ns1__downloadCACUpdateFile *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__downloadCACUpdateFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__uploadCACData
#define SOAP_TYPE___ns1__uploadCACData (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__uploadCACData(struct soap*, struct __ns1__uploadCACData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__uploadCACData(struct soap*, const struct __ns1__uploadCACData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__uploadCACData(struct soap*, const char*, int, const struct __ns1__uploadCACData *, const char*);
SOAP_FMAC3 struct __ns1__uploadCACData * SOAP_FMAC4 soap_in___ns1__uploadCACData(struct soap*, const char*, struct __ns1__uploadCACData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__uploadCACData(struct soap*, const struct __ns1__uploadCACData *, const char*, const char*);

#ifndef soap_write___ns1__uploadCACData
#define soap_write___ns1__uploadCACData(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__uploadCACData(soap, data, "-ns1:uploadCACData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__uploadCACData * SOAP_FMAC4 soap_get___ns1__uploadCACData(struct soap*, struct __ns1__uploadCACData *, const char*, const char*);

#ifndef soap_read___ns1__uploadCACData
#define soap_read___ns1__uploadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__uploadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__uploadCACData * SOAP_FMAC2 soap_instantiate___ns1__uploadCACData(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__uploadCACData * soap_new___ns1__uploadCACData(struct soap *soap, int n = -1) { return soap_instantiate___ns1__uploadCACData(soap, n, NULL, NULL, NULL); }

inline struct __ns1__uploadCACData * soap_new_req___ns1__uploadCACData(struct soap *soap) { struct __ns1__uploadCACData *_p = soap_instantiate___ns1__uploadCACData(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__uploadCACData * soap_new_set___ns1__uploadCACData(struct soap *soap, _ns1__uploadCACData *ns1__uploadCACData) { struct __ns1__uploadCACData *_p = soap_instantiate___ns1__uploadCACData(soap, -1, NULL, NULL, NULL); _p->ns1__uploadCACData = ns1__uploadCACData; return _p; }

inline void soap_delete___ns1__uploadCACData(struct soap *soap, struct __ns1__uploadCACData *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__uploadCACData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACHistoryVersionResponse
#define SOAP_TYPE_PointerTo_ns1__downloadCACHistoryVersionResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACHistoryVersionResponse(struct soap*, _ns1__downloadCACHistoryVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACHistoryVersionResponse(struct soap*, const char *, int, _ns1__downloadCACHistoryVersionResponse *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACHistoryVersionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACHistoryVersionResponse(struct soap*, const char*, _ns1__downloadCACHistoryVersionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACHistoryVersionResponse(struct soap*, _ns1__downloadCACHistoryVersionResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACHistoryVersionResponse
#define soap_write_PointerTo_ns1__downloadCACHistoryVersionResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACHistoryVersionResponse(soap, data, "ns1:downloadCACHistoryVersionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACHistoryVersionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACHistoryVersionResponse(struct soap*, _ns1__downloadCACHistoryVersionResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACHistoryVersionResponse
#define soap_read_PointerTo_ns1__downloadCACHistoryVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACHistoryVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACHistoryVersion
#define SOAP_TYPE_PointerTo_ns1__downloadCACHistoryVersion (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACHistoryVersion(struct soap*, _ns1__downloadCACHistoryVersion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACHistoryVersion(struct soap*, const char *, int, _ns1__downloadCACHistoryVersion *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACHistoryVersion ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACHistoryVersion(struct soap*, const char*, _ns1__downloadCACHistoryVersion **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACHistoryVersion(struct soap*, _ns1__downloadCACHistoryVersion *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACHistoryVersion
#define soap_write_PointerTo_ns1__downloadCACHistoryVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACHistoryVersion(soap, data, "ns1:downloadCACHistoryVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACHistoryVersion ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACHistoryVersion(struct soap*, _ns1__downloadCACHistoryVersion **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACHistoryVersion
#define soap_read_PointerTo_ns1__downloadCACHistoryVersion(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACHistoryVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACConfigResponse
#define SOAP_TYPE_PointerTo_ns1__uploadCACConfigResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACConfigResponse(struct soap*, _ns1__uploadCACConfigResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACConfigResponse(struct soap*, const char *, int, _ns1__uploadCACConfigResponse *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACConfigResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACConfigResponse(struct soap*, const char*, _ns1__uploadCACConfigResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACConfigResponse(struct soap*, _ns1__uploadCACConfigResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACConfigResponse
#define soap_write_PointerTo_ns1__uploadCACConfigResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACConfigResponse(soap, data, "ns1:uploadCACConfigResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACConfigResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACConfigResponse(struct soap*, _ns1__uploadCACConfigResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACConfigResponse
#define soap_read_PointerTo_ns1__uploadCACConfigResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACConfigResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACConfig
#define SOAP_TYPE_PointerTo_ns1__uploadCACConfig (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACConfig(struct soap*, _ns1__uploadCACConfig *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACConfig(struct soap*, const char *, int, _ns1__uploadCACConfig *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACConfig ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACConfig(struct soap*, const char*, _ns1__uploadCACConfig **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACConfig(struct soap*, _ns1__uploadCACConfig *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACConfig
#define soap_write_PointerTo_ns1__uploadCACConfig(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACConfig(soap, data, "ns1:uploadCACConfig", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACConfig ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACConfig(struct soap*, _ns1__uploadCACConfig **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACConfig
#define soap_read_PointerTo_ns1__uploadCACConfig(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACConfig(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACHeartbeatInfoResponse
#define SOAP_TYPE_PointerTo_ns1__uploadCACHeartbeatInfoResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACHeartbeatInfoResponse(struct soap*, _ns1__uploadCACHeartbeatInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACHeartbeatInfoResponse(struct soap*, const char *, int, _ns1__uploadCACHeartbeatInfoResponse *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACHeartbeatInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACHeartbeatInfoResponse(struct soap*, const char*, _ns1__uploadCACHeartbeatInfoResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACHeartbeatInfoResponse(struct soap*, _ns1__uploadCACHeartbeatInfoResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACHeartbeatInfoResponse
#define soap_write_PointerTo_ns1__uploadCACHeartbeatInfoResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACHeartbeatInfoResponse(soap, data, "ns1:uploadCACHeartbeatInfoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACHeartbeatInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACHeartbeatInfoResponse(struct soap*, _ns1__uploadCACHeartbeatInfoResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACHeartbeatInfoResponse
#define soap_read_PointerTo_ns1__uploadCACHeartbeatInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACHeartbeatInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACHeartbeatInfo
#define SOAP_TYPE_PointerTo_ns1__uploadCACHeartbeatInfo (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACHeartbeatInfo(struct soap*, _ns1__uploadCACHeartbeatInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACHeartbeatInfo(struct soap*, const char *, int, _ns1__uploadCACHeartbeatInfo *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACHeartbeatInfo ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACHeartbeatInfo(struct soap*, const char*, _ns1__uploadCACHeartbeatInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACHeartbeatInfo(struct soap*, _ns1__uploadCACHeartbeatInfo *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACHeartbeatInfo
#define soap_write_PointerTo_ns1__uploadCACHeartbeatInfo(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACHeartbeatInfo(soap, data, "ns1:uploadCACHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACHeartbeatInfo ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACHeartbeatInfo(struct soap*, _ns1__uploadCACHeartbeatInfo **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACHeartbeatInfo
#define soap_read_PointerTo_ns1__uploadCACHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACLatestVersionResponse
#define SOAP_TYPE_PointerTo_ns1__downloadCACLatestVersionResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACLatestVersionResponse(struct soap*, _ns1__downloadCACLatestVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACLatestVersionResponse(struct soap*, const char *, int, _ns1__downloadCACLatestVersionResponse *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACLatestVersionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACLatestVersionResponse(struct soap*, const char*, _ns1__downloadCACLatestVersionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACLatestVersionResponse(struct soap*, _ns1__downloadCACLatestVersionResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACLatestVersionResponse
#define soap_write_PointerTo_ns1__downloadCACLatestVersionResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACLatestVersionResponse(soap, data, "ns1:downloadCACLatestVersionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACLatestVersionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACLatestVersionResponse(struct soap*, _ns1__downloadCACLatestVersionResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACLatestVersionResponse
#define soap_read_PointerTo_ns1__downloadCACLatestVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACLatestVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACLatestVersion
#define SOAP_TYPE_PointerTo_ns1__downloadCACLatestVersion (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACLatestVersion(struct soap*, _ns1__downloadCACLatestVersion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACLatestVersion(struct soap*, const char *, int, _ns1__downloadCACLatestVersion *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACLatestVersion ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACLatestVersion(struct soap*, const char*, _ns1__downloadCACLatestVersion **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACLatestVersion(struct soap*, _ns1__downloadCACLatestVersion *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACLatestVersion
#define soap_write_PointerTo_ns1__downloadCACLatestVersion(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACLatestVersion(soap, data, "ns1:downloadCACLatestVersion", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACLatestVersion ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACLatestVersion(struct soap*, _ns1__downloadCACLatestVersion **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACLatestVersion
#define soap_read_PointerTo_ns1__downloadCACLatestVersion(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACLatestVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACUpdateFileResponse
#define SOAP_TYPE_PointerTo_ns1__downloadCACUpdateFileResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACUpdateFileResponse(struct soap*, _ns1__downloadCACUpdateFileResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACUpdateFileResponse(struct soap*, const char *, int, _ns1__downloadCACUpdateFileResponse *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACUpdateFileResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACUpdateFileResponse(struct soap*, const char*, _ns1__downloadCACUpdateFileResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACUpdateFileResponse(struct soap*, _ns1__downloadCACUpdateFileResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACUpdateFileResponse
#define soap_write_PointerTo_ns1__downloadCACUpdateFileResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACUpdateFileResponse(soap, data, "ns1:downloadCACUpdateFileResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACUpdateFileResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACUpdateFileResponse(struct soap*, _ns1__downloadCACUpdateFileResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACUpdateFileResponse
#define soap_read_PointerTo_ns1__downloadCACUpdateFileResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACUpdateFileResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__downloadCACUpdateFile
#define SOAP_TYPE_PointerTo_ns1__downloadCACUpdateFile (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__downloadCACUpdateFile(struct soap*, _ns1__downloadCACUpdateFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__downloadCACUpdateFile(struct soap*, const char *, int, _ns1__downloadCACUpdateFile *const*, const char *);
SOAP_FMAC3 _ns1__downloadCACUpdateFile ** SOAP_FMAC4 soap_in_PointerTo_ns1__downloadCACUpdateFile(struct soap*, const char*, _ns1__downloadCACUpdateFile **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__downloadCACUpdateFile(struct soap*, _ns1__downloadCACUpdateFile *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__downloadCACUpdateFile
#define soap_write_PointerTo_ns1__downloadCACUpdateFile(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__downloadCACUpdateFile(soap, data, "ns1:downloadCACUpdateFile", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__downloadCACUpdateFile ** SOAP_FMAC4 soap_get_PointerTo_ns1__downloadCACUpdateFile(struct soap*, _ns1__downloadCACUpdateFile **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__downloadCACUpdateFile
#define soap_read_PointerTo_ns1__downloadCACUpdateFile(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__downloadCACUpdateFile(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACDataResponse
#define SOAP_TYPE_PointerTo_ns1__uploadCACDataResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACDataResponse(struct soap*, _ns1__uploadCACDataResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACDataResponse(struct soap*, const char *, int, _ns1__uploadCACDataResponse *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACDataResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACDataResponse(struct soap*, const char*, _ns1__uploadCACDataResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACDataResponse(struct soap*, _ns1__uploadCACDataResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACDataResponse
#define soap_write_PointerTo_ns1__uploadCACDataResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACDataResponse(soap, data, "ns1:uploadCACDataResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACDataResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACDataResponse(struct soap*, _ns1__uploadCACDataResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACDataResponse
#define soap_read_PointerTo_ns1__uploadCACDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__uploadCACData
#define SOAP_TYPE_PointerTo_ns1__uploadCACData (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCACData(struct soap*, _ns1__uploadCACData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCACData(struct soap*, const char *, int, _ns1__uploadCACData *const*, const char *);
SOAP_FMAC3 _ns1__uploadCACData ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCACData(struct soap*, const char*, _ns1__uploadCACData **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCACData(struct soap*, _ns1__uploadCACData *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCACData
#define soap_write_PointerTo_ns1__uploadCACData(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__uploadCACData(soap, data, "ns1:uploadCACData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCACData ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCACData(struct soap*, _ns1__uploadCACData **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCACData
#define soap_read_PointerTo_ns1__uploadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

/* End of soapH.h */
