/* CAGAccessService.h
   Generated by wsdl2h 2.8.4 from CAGAccessService.wsdl and typemap.dat
   2013-09-30 02:25:59 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on CAGAccessService.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
//gsoap ns1   schema namespace:	http://tempuri.org/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class _ns1__uploadCMAData.
class _ns1__uploadCMAData;

//  Forward declaration of class _ns1__uploadCMADataResponse.
class _ns1__uploadCMADataResponse;

//  Forward declaration of class _ns1__uploadCMAHeartbeatInfo.
class _ns1__uploadCMAHeartbeatInfo;

//  Forward declaration of class _ns1__uploadCMAHeartbeatInfoResponse.
class _ns1__uploadCMAHeartbeatInfoResponse;

//  Forward declaration of class _ns1__upLoadCACData.
class _ns1__upLoadCACData;

//  Forward declaration of class _ns1__upLoadCACDataResponse.
class _ns1__upLoadCACDataResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://tempuri.org/":uploadCMAData

/// "http://tempuri.org/":uploadCMAData is a complexType.
class _ns1__uploadCMAData
{ public:
/// Element sXml of type xs:string.
    std::string*                         sXml                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://tempuri.org/":uploadCMADataResponse

/// "http://tempuri.org/":uploadCMADataResponse is a complexType.
class _ns1__uploadCMADataResponse
{ public:
/// Element uploadCMADataResult of type xs:string.
    std::string*                         uploadCMADataResult            0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://tempuri.org/":uploadCMAHeartbeatInfo

/// "http://tempuri.org/":uploadCMAHeartbeatInfo is a complexType.
class _ns1__uploadCMAHeartbeatInfo
{ public:
/// Element sXml of type xs:string.
    std::string*                         sXml                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://tempuri.org/":uploadCMAHeartbeatInfoResponse

/// "http://tempuri.org/":uploadCMAHeartbeatInfoResponse is a complexType.
class _ns1__uploadCMAHeartbeatInfoResponse
{ public:
/// Element uploadCMAHeartbeatInfoResult of type xs:string.
    std::string*                         uploadCMAHeartbeatInfoResult   0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://tempuri.org/":upLoadCACData

/// "http://tempuri.org/":upLoadCACData is a complexType.
class _ns1__upLoadCACData
{ public:
/// Element sXml of type xs:string.
    std::string*                         sXml                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://tempuri.org/":upLoadCACDataResponse

/// "http://tempuri.org/":upLoadCACDataResponse is a complexType.
class _ns1__upLoadCACDataResponse
{ public:
/// Element upLoadCACDataResult of type xs:string.
    std::string*                         upLoadCACDataResult            0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	CAGWebServicePortSoap 
//gsoap ns2  service type:	CAGWebServicePortSoap 
//gsoap ns2  service port:	http://172.168.1.233:8080/CAGService.asmx 
//gsoap ns2  service namespace:	http://tempuri.org/CAGWebServicePortSoap 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ns3  service name:	CAGWebServicePortSoap12 
//gsoap ns3  service type:	CAGWebServicePortSoap 
//gsoap ns3  service port:	http://172.168.1.233:8080/CAGService.asmx 
//gsoap ns3  service namespace:	http://tempuri.org/CAGWebServicePortSoap12 
//gsoap ns3  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref CAGWebServicePortSoap

  - @ref CAGWebServicePortSoap12

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page CAGWebServicePortSoap Binding "CAGWebServicePortSoap"

@section CAGWebServicePortSoap_operations Operations of Binding  "CAGWebServicePortSoap"

  - @ref __ns2__uploadCMAData

  - @ref __ns2__uploadCMAHeartbeatInfo

  - @ref __ns2__upLoadCACData

@section CAGWebServicePortSoap_ports Endpoints of Binding  "CAGWebServicePortSoap"

  - http://172.168.1.233:8080/CAGService.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page CAGWebServicePortSoap12 Binding "CAGWebServicePortSoap12"

@section CAGWebServicePortSoap12_operations Operations of Binding  "CAGWebServicePortSoap12"

  - @ref __ns3__uploadCMAData

  - @ref __ns3__uploadCMAHeartbeatInfo

  - @ref __ns3__upLoadCACData

@section CAGWebServicePortSoap12_ports Endpoints of Binding  "CAGWebServicePortSoap12"

  - http://172.168.1.233:8080/CAGService.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   CAGWebServicePortSoap                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__uploadCMAData                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__uploadCMAData" of service binding "CAGWebServicePortSoap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/uploadCMAData"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAData"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMADataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__uploadCMAData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__uploadCMAData*                ns1__uploadCMAData,
    // response parameters:
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__uploadCMAData(
    struct soap *soap,
    // request parameters:
    _ns1__uploadCMAData*                ns1__uploadCMAData,
    // response parameters:
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoapProxy.h):
@code
  class CAGWebServicePortSoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoapService.h):
@code
  class CAGWebServicePortSoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns2  service method-style:	uploadCMAData document
//gsoap ns2  service method-encoding:	uploadCMAData literal
//gsoap ns2  service method-action:	uploadCMAData http://tempuri.org/uploadCMAData
//gsoap ns2  service method-output-action:	uploadCMAData http://tempuri.org//CAGWebServicePortSoap/uploadCMADataResponse
int __ns2__uploadCMAData(
    _ns1__uploadCMAData*                ns1__uploadCMAData,	///< Request parameter
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__uploadCMAHeartbeatInfo                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__uploadCMAHeartbeatInfo" of service binding "CAGWebServicePortSoap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/uploadCMAHeartbeatInfo"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfo"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfoResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__uploadCMAHeartbeatInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,
    // response parameters:
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__uploadCMAHeartbeatInfo(
    struct soap *soap,
    // request parameters:
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,
    // response parameters:
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoapProxy.h):
@code
  class CAGWebServicePortSoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoapService.h):
@code
  class CAGWebServicePortSoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns2  service method-style:	uploadCMAHeartbeatInfo document
//gsoap ns2  service method-encoding:	uploadCMAHeartbeatInfo literal
//gsoap ns2  service method-action:	uploadCMAHeartbeatInfo http://tempuri.org/uploadCMAHeartbeatInfo
//gsoap ns2  service method-output-action:	uploadCMAHeartbeatInfo http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfoResponse
int __ns2__uploadCMAHeartbeatInfo(
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,	///< Request parameter
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__upLoadCACData                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__upLoadCACData" of service binding "CAGWebServicePortSoap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/upLoadCACData"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/upLoadCACData"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/upLoadCACDataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__upLoadCACData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__upLoadCACData*                ns1__upLoadCACData,
    // response parameters:
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__upLoadCACData(
    struct soap *soap,
    // request parameters:
    _ns1__upLoadCACData*                ns1__upLoadCACData,
    // response parameters:
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoapProxy.h):
@code
  class CAGWebServicePortSoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoapService.h):
@code
  class CAGWebServicePortSoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns2  service method-style:	upLoadCACData document
//gsoap ns2  service method-encoding:	upLoadCACData literal
//gsoap ns2  service method-action:	upLoadCACData http://tempuri.org/upLoadCACData
//gsoap ns2  service method-output-action:	upLoadCACData http://tempuri.org//CAGWebServicePortSoap/upLoadCACDataResponse
int __ns2__upLoadCACData(
    _ns1__upLoadCACData*                ns1__upLoadCACData,	///< Request parameter
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   CAGWebServicePortSoap12                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns3__uploadCMAData                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns3__uploadCMAData" of service binding "CAGWebServicePortSoap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/uploadCMAData"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAData"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMADataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns3__uploadCMAData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__uploadCMAData*                ns1__uploadCMAData,
    // response parameters:
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns3__uploadCMAData(
    struct soap *soap,
    // request parameters:
    _ns1__uploadCMAData*                ns1__uploadCMAData,
    // response parameters:
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoap12Proxy.h):
@code
  class CAGWebServicePortSoap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoap12Service.h):
@code
  class CAGWebServicePortSoap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns3  service method-style:	uploadCMAData document
//gsoap ns3  service method-encoding:	uploadCMAData literal
//gsoap ns3  service method-action:	uploadCMAData http://tempuri.org/uploadCMAData
//gsoap ns3  service method-output-action:	uploadCMAData http://tempuri.org//CAGWebServicePortSoap/uploadCMADataResponse
int __ns3__uploadCMAData(
    _ns1__uploadCMAData*                ns1__uploadCMAData,	///< Request parameter
    _ns1__uploadCMADataResponse*        ns1__uploadCMADataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns3__uploadCMAHeartbeatInfo                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns3__uploadCMAHeartbeatInfo" of service binding "CAGWebServicePortSoap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/uploadCMAHeartbeatInfo"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfo"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfoResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns3__uploadCMAHeartbeatInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,
    // response parameters:
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns3__uploadCMAHeartbeatInfo(
    struct soap *soap,
    // request parameters:
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,
    // response parameters:
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoap12Proxy.h):
@code
  class CAGWebServicePortSoap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoap12Service.h):
@code
  class CAGWebServicePortSoap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns3  service method-style:	uploadCMAHeartbeatInfo document
//gsoap ns3  service method-encoding:	uploadCMAHeartbeatInfo literal
//gsoap ns3  service method-action:	uploadCMAHeartbeatInfo http://tempuri.org/uploadCMAHeartbeatInfo
//gsoap ns3  service method-output-action:	uploadCMAHeartbeatInfo http://tempuri.org//CAGWebServicePortSoap/uploadCMAHeartbeatInfoResponse
int __ns3__uploadCMAHeartbeatInfo(
    _ns1__uploadCMAHeartbeatInfo*       ns1__uploadCMAHeartbeatInfo,	///< Request parameter
    _ns1__uploadCMAHeartbeatInfoResponse* ns1__uploadCMAHeartbeatInfoResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns3__upLoadCACData                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns3__upLoadCACData" of service binding "CAGWebServicePortSoap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://tempuri.org/upLoadCACData"

  - Addressing action: "http://tempuri.org//CAGWebServicePortSoap/upLoadCACData"

  - Addressing response action: "http://tempuri.org//CAGWebServicePortSoap/upLoadCACDataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns3__upLoadCACData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ns1__upLoadCACData*                ns1__upLoadCACData,
    // response parameters:
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns3__upLoadCACData(
    struct soap *soap,
    // request parameters:
    _ns1__upLoadCACData*                ns1__upLoadCACData,
    // response parameters:
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse
  );
@endcode

C++ proxy class (defined in soapCAGWebServicePortSoap12Proxy.h):
@code
  class CAGWebServicePortSoap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapCAGWebServicePortSoap12Service.h):
@code
  class CAGWebServicePortSoap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns3  service method-style:	upLoadCACData document
//gsoap ns3  service method-encoding:	upLoadCACData literal
//gsoap ns3  service method-action:	upLoadCACData http://tempuri.org/upLoadCACData
//gsoap ns3  service method-output-action:	upLoadCACData http://tempuri.org//CAGWebServicePortSoap/upLoadCACDataResponse
int __ns3__upLoadCACData(
    _ns1__upLoadCACData*                ns1__upLoadCACData,	///< Request parameter
    _ns1__upLoadCACDataResponse*        ns1__upLoadCACDataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://tempuri.org/"

  - <ns1:uploadCMAData> @ref _ns1__uploadCMAData
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData*);
    @endcode

  - <ns1:uploadCMADataResponse> @ref _ns1__uploadCMADataResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse*);
    @endcode

  - <ns1:uploadCMAHeartbeatInfo> @ref _ns1__uploadCMAHeartbeatInfo
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo*);
    @endcode

  - <ns1:uploadCMAHeartbeatInfoResponse> @ref _ns1__uploadCMAHeartbeatInfoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse*);
    @endcode

  - <ns1:upLoadCACData> @ref _ns1__upLoadCACData
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData*);
    @endcode

  - <ns1:upLoadCACDataResponse> @ref _ns1__upLoadCACDataResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse*);
    @endcode

*/

/* End of CAGAccessService.h */
