/* soapCAGWebServicePortSoapProxy.h
   Generated by gSOAP 2.8.4 from CAGAccessService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapCAGWebServicePortSoapProxy_H
#define soapCAGWebServicePortSoapProxy_H
#include "soapH.h"

class SOAP_CMAC CAGWebServicePortSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'CAGWebServicePortSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	CAGWebServicePortSoapProxy();
	/// Constructor with copy of another engine state
	CAGWebServicePortSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	CAGWebServicePortSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	CAGWebServicePortSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	CAGWebServicePortSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	CAGWebServicePortSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~CAGWebServicePortSoapProxy();
	/// Initializer used by constructors
	virtual	void CAGWebServicePortSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'uploadCMAData' (returns error code or SOAP_OK)
	virtual	int uploadCMAData(_ns1__uploadCMAData *ns1__uploadCMAData, _ns1__uploadCMADataResponse *ns1__uploadCMADataResponse) { return uploadCMAData(NULL, NULL, ns1__uploadCMAData, ns1__uploadCMADataResponse); }
	virtual	int uploadCMAData(const char *endpoint, const char *soap_action, _ns1__uploadCMAData *ns1__uploadCMAData, _ns1__uploadCMADataResponse *ns1__uploadCMADataResponse);

	/// Web service operation 'uploadCMAHeartbeatInfo' (returns error code or SOAP_OK)
	virtual	int uploadCMAHeartbeatInfo(_ns1__uploadCMAHeartbeatInfo *ns1__uploadCMAHeartbeatInfo, _ns1__uploadCMAHeartbeatInfoResponse *ns1__uploadCMAHeartbeatInfoResponse) { return uploadCMAHeartbeatInfo(NULL, NULL, ns1__uploadCMAHeartbeatInfo, ns1__uploadCMAHeartbeatInfoResponse); }
	virtual	int uploadCMAHeartbeatInfo(const char *endpoint, const char *soap_action, _ns1__uploadCMAHeartbeatInfo *ns1__uploadCMAHeartbeatInfo, _ns1__uploadCMAHeartbeatInfoResponse *ns1__uploadCMAHeartbeatInfoResponse);

	/// Web service operation 'upLoadCACData' (returns error code or SOAP_OK)
	virtual	int upLoadCACData(_ns1__upLoadCACData *ns1__upLoadCACData, _ns1__upLoadCACDataResponse *ns1__upLoadCACDataResponse) { return upLoadCACData(NULL, NULL, ns1__upLoadCACData, ns1__upLoadCACDataResponse); }
	virtual	int upLoadCACData(const char *endpoint, const char *soap_action, _ns1__upLoadCACData *ns1__upLoadCACData, _ns1__upLoadCACDataResponse *ns1__upLoadCACDataResponse);
};
#endif
