/* soapH.h
   Generated by gSOAP 2.8.4 from CAGAccessService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__upLoadCACDataResponse
#define SOAP_TYPE__ns1__upLoadCACDataResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__upLoadCACDataResponse(struct soap*, const char*, int, const _ns1__upLoadCACDataResponse *, const char*);
SOAP_FMAC3 _ns1__upLoadCACDataResponse * SOAP_FMAC4 soap_in__ns1__upLoadCACDataResponse(struct soap*, const char*, _ns1__upLoadCACDataResponse *, const char*);

#ifndef soap_write__ns1__upLoadCACDataResponse
#define soap_write__ns1__upLoadCACDataResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:upLoadCACDataResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__upLoadCACDataResponse
#define soap_read__ns1__upLoadCACDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__upLoadCACDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__upLoadCACDataResponse * SOAP_FMAC4 soap_get__ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse *, const char*, const char*);

#define soap_new__ns1__upLoadCACDataResponse(soap, n) soap_instantiate__ns1__upLoadCACDataResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__upLoadCACDataResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__upLoadCACDataResponse * SOAP_FMAC2 soap_instantiate__ns1__upLoadCACDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__upLoadCACDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__upLoadCACData
#define SOAP_TYPE__ns1__upLoadCACData (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__upLoadCACData(struct soap*, const char*, int, const _ns1__upLoadCACData *, const char*);
SOAP_FMAC3 _ns1__upLoadCACData * SOAP_FMAC4 soap_in__ns1__upLoadCACData(struct soap*, const char*, _ns1__upLoadCACData *, const char*);

#ifndef soap_write__ns1__upLoadCACData
#define soap_write__ns1__upLoadCACData(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:upLoadCACData", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__upLoadCACData
#define soap_read__ns1__upLoadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__upLoadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__upLoadCACData * SOAP_FMAC4 soap_get__ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData *, const char*, const char*);

#define soap_new__ns1__upLoadCACData(soap, n) soap_instantiate__ns1__upLoadCACData(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__upLoadCACData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__upLoadCACData * SOAP_FMAC2 soap_instantiate__ns1__upLoadCACData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__upLoadCACData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCMAHeartbeatInfoResponse
#define SOAP_TYPE__ns1__uploadCMAHeartbeatInfoResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, const char*, int, const _ns1__uploadCMAHeartbeatInfoResponse *, const char*);
SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfoResponse * SOAP_FMAC4 soap_in__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, const char*, _ns1__uploadCMAHeartbeatInfoResponse *, const char*);

#ifndef soap_write__ns1__uploadCMAHeartbeatInfoResponse
#define soap_write__ns1__uploadCMAHeartbeatInfoResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:uploadCMAHeartbeatInfoResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__uploadCMAHeartbeatInfoResponse
#define soap_read__ns1__uploadCMAHeartbeatInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCMAHeartbeatInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfoResponse * SOAP_FMAC4 soap_get__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse *, const char*, const char*);

#define soap_new__ns1__uploadCMAHeartbeatInfoResponse(soap, n) soap_instantiate__ns1__uploadCMAHeartbeatInfoResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__uploadCMAHeartbeatInfoResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__uploadCMAHeartbeatInfoResponse * SOAP_FMAC2 soap_instantiate__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCMAHeartbeatInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCMAHeartbeatInfo
#define SOAP_TYPE__ns1__uploadCMAHeartbeatInfo (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCMAHeartbeatInfo(struct soap*, const char*, int, const _ns1__uploadCMAHeartbeatInfo *, const char*);
SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_in__ns1__uploadCMAHeartbeatInfo(struct soap*, const char*, _ns1__uploadCMAHeartbeatInfo *, const char*);

#ifndef soap_write__ns1__uploadCMAHeartbeatInfo
#define soap_write__ns1__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:uploadCMAHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__uploadCMAHeartbeatInfo
#define soap_read__ns1__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCMAHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_get__ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo *, const char*, const char*);

#define soap_new__ns1__uploadCMAHeartbeatInfo(soap, n) soap_instantiate__ns1__uploadCMAHeartbeatInfo(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__uploadCMAHeartbeatInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__uploadCMAHeartbeatInfo * SOAP_FMAC2 soap_instantiate__ns1__uploadCMAHeartbeatInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCMAHeartbeatInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCMADataResponse
#define SOAP_TYPE__ns1__uploadCMADataResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCMADataResponse(struct soap*, const char*, int, const _ns1__uploadCMADataResponse *, const char*);
SOAP_FMAC3 _ns1__uploadCMADataResponse * SOAP_FMAC4 soap_in__ns1__uploadCMADataResponse(struct soap*, const char*, _ns1__uploadCMADataResponse *, const char*);

#ifndef soap_write__ns1__uploadCMADataResponse
#define soap_write__ns1__uploadCMADataResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:uploadCMADataResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__uploadCMADataResponse
#define soap_read__ns1__uploadCMADataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCMADataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMADataResponse * SOAP_FMAC4 soap_get__ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse *, const char*, const char*);

#define soap_new__ns1__uploadCMADataResponse(soap, n) soap_instantiate__ns1__uploadCMADataResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__uploadCMADataResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__uploadCMADataResponse * SOAP_FMAC2 soap_instantiate__ns1__uploadCMADataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCMADataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__uploadCMAData
#define SOAP_TYPE__ns1__uploadCMAData (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__uploadCMAData(struct soap*, const char*, int, const _ns1__uploadCMAData *, const char*);
SOAP_FMAC3 _ns1__uploadCMAData * SOAP_FMAC4 soap_in__ns1__uploadCMAData(struct soap*, const char*, _ns1__uploadCMAData *, const char*);

#ifndef soap_write__ns1__uploadCMAData
#define soap_write__ns1__uploadCMAData(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:uploadCMAData", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__uploadCMAData
#define soap_read__ns1__uploadCMAData(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__uploadCMAData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAData * SOAP_FMAC4 soap_get__ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData *, const char*, const char*);

#define soap_new__ns1__uploadCMAData(soap, n) soap_instantiate__ns1__uploadCMAData(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__uploadCMAData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__uploadCMAData * SOAP_FMAC2 soap_instantiate__ns1__uploadCMAData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__uploadCMAData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns3__upLoadCACData
#define SOAP_TYPE___ns3__upLoadCACData (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__upLoadCACData(struct soap*, struct __ns3__upLoadCACData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__upLoadCACData(struct soap*, const struct __ns3__upLoadCACData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__upLoadCACData(struct soap*, const char*, int, const struct __ns3__upLoadCACData *, const char*);
SOAP_FMAC3 struct __ns3__upLoadCACData * SOAP_FMAC4 soap_in___ns3__upLoadCACData(struct soap*, const char*, struct __ns3__upLoadCACData *, const char*);

#ifndef soap_write___ns3__upLoadCACData
#define soap_write___ns3__upLoadCACData(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__upLoadCACData(soap, data), 0) || soap_put___ns3__upLoadCACData(soap, data, "-ns3:upLoadCACData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__upLoadCACData(struct soap*, const struct __ns3__upLoadCACData *, const char*, const char*);

#ifndef soap_read___ns3__upLoadCACData
#define soap_read___ns3__upLoadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__upLoadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__upLoadCACData * SOAP_FMAC4 soap_get___ns3__upLoadCACData(struct soap*, struct __ns3__upLoadCACData *, const char*, const char*);

#define soap_new___ns3__upLoadCACData(soap, n) soap_instantiate___ns3__upLoadCACData(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__upLoadCACData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__upLoadCACData * SOAP_FMAC2 soap_instantiate___ns3__upLoadCACData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__upLoadCACData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__uploadCMAHeartbeatInfo
#define SOAP_TYPE___ns3__uploadCMAHeartbeatInfo (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__uploadCMAHeartbeatInfo(struct soap*, struct __ns3__uploadCMAHeartbeatInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__uploadCMAHeartbeatInfo(struct soap*, const struct __ns3__uploadCMAHeartbeatInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__uploadCMAHeartbeatInfo(struct soap*, const char*, int, const struct __ns3__uploadCMAHeartbeatInfo *, const char*);
SOAP_FMAC3 struct __ns3__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_in___ns3__uploadCMAHeartbeatInfo(struct soap*, const char*, struct __ns3__uploadCMAHeartbeatInfo *, const char*);

#ifndef soap_write___ns3__uploadCMAHeartbeatInfo
#define soap_write___ns3__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__uploadCMAHeartbeatInfo(soap, data), 0) || soap_put___ns3__uploadCMAHeartbeatInfo(soap, data, "-ns3:uploadCMAHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__uploadCMAHeartbeatInfo(struct soap*, const struct __ns3__uploadCMAHeartbeatInfo *, const char*, const char*);

#ifndef soap_read___ns3__uploadCMAHeartbeatInfo
#define soap_read___ns3__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__uploadCMAHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_get___ns3__uploadCMAHeartbeatInfo(struct soap*, struct __ns3__uploadCMAHeartbeatInfo *, const char*, const char*);

#define soap_new___ns3__uploadCMAHeartbeatInfo(soap, n) soap_instantiate___ns3__uploadCMAHeartbeatInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__uploadCMAHeartbeatInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__uploadCMAHeartbeatInfo * SOAP_FMAC2 soap_instantiate___ns3__uploadCMAHeartbeatInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__uploadCMAHeartbeatInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__uploadCMAData
#define SOAP_TYPE___ns3__uploadCMAData (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__uploadCMAData(struct soap*, struct __ns3__uploadCMAData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__uploadCMAData(struct soap*, const struct __ns3__uploadCMAData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__uploadCMAData(struct soap*, const char*, int, const struct __ns3__uploadCMAData *, const char*);
SOAP_FMAC3 struct __ns3__uploadCMAData * SOAP_FMAC4 soap_in___ns3__uploadCMAData(struct soap*, const char*, struct __ns3__uploadCMAData *, const char*);

#ifndef soap_write___ns3__uploadCMAData
#define soap_write___ns3__uploadCMAData(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__uploadCMAData(soap, data), 0) || soap_put___ns3__uploadCMAData(soap, data, "-ns3:uploadCMAData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__uploadCMAData(struct soap*, const struct __ns3__uploadCMAData *, const char*, const char*);

#ifndef soap_read___ns3__uploadCMAData
#define soap_read___ns3__uploadCMAData(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__uploadCMAData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__uploadCMAData * SOAP_FMAC4 soap_get___ns3__uploadCMAData(struct soap*, struct __ns3__uploadCMAData *, const char*, const char*);

#define soap_new___ns3__uploadCMAData(soap, n) soap_instantiate___ns3__uploadCMAData(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__uploadCMAData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__uploadCMAData * SOAP_FMAC2 soap_instantiate___ns3__uploadCMAData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__uploadCMAData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__upLoadCACData
#define SOAP_TYPE___ns2__upLoadCACData (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__upLoadCACData(struct soap*, struct __ns2__upLoadCACData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__upLoadCACData(struct soap*, const struct __ns2__upLoadCACData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__upLoadCACData(struct soap*, const char*, int, const struct __ns2__upLoadCACData *, const char*);
SOAP_FMAC3 struct __ns2__upLoadCACData * SOAP_FMAC4 soap_in___ns2__upLoadCACData(struct soap*, const char*, struct __ns2__upLoadCACData *, const char*);

#ifndef soap_write___ns2__upLoadCACData
#define soap_write___ns2__upLoadCACData(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__upLoadCACData(soap, data), 0) || soap_put___ns2__upLoadCACData(soap, data, "-ns2:upLoadCACData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__upLoadCACData(struct soap*, const struct __ns2__upLoadCACData *, const char*, const char*);

#ifndef soap_read___ns2__upLoadCACData
#define soap_read___ns2__upLoadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__upLoadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__upLoadCACData * SOAP_FMAC4 soap_get___ns2__upLoadCACData(struct soap*, struct __ns2__upLoadCACData *, const char*, const char*);

#define soap_new___ns2__upLoadCACData(soap, n) soap_instantiate___ns2__upLoadCACData(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__upLoadCACData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__upLoadCACData * SOAP_FMAC2 soap_instantiate___ns2__upLoadCACData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__upLoadCACData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__uploadCMAHeartbeatInfo
#define SOAP_TYPE___ns2__uploadCMAHeartbeatInfo (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__uploadCMAHeartbeatInfo(struct soap*, struct __ns2__uploadCMAHeartbeatInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__uploadCMAHeartbeatInfo(struct soap*, const struct __ns2__uploadCMAHeartbeatInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__uploadCMAHeartbeatInfo(struct soap*, const char*, int, const struct __ns2__uploadCMAHeartbeatInfo *, const char*);
SOAP_FMAC3 struct __ns2__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_in___ns2__uploadCMAHeartbeatInfo(struct soap*, const char*, struct __ns2__uploadCMAHeartbeatInfo *, const char*);

#ifndef soap_write___ns2__uploadCMAHeartbeatInfo
#define soap_write___ns2__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__uploadCMAHeartbeatInfo(soap, data), 0) || soap_put___ns2__uploadCMAHeartbeatInfo(soap, data, "-ns2:uploadCMAHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__uploadCMAHeartbeatInfo(struct soap*, const struct __ns2__uploadCMAHeartbeatInfo *, const char*, const char*);

#ifndef soap_read___ns2__uploadCMAHeartbeatInfo
#define soap_read___ns2__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__uploadCMAHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__uploadCMAHeartbeatInfo * SOAP_FMAC4 soap_get___ns2__uploadCMAHeartbeatInfo(struct soap*, struct __ns2__uploadCMAHeartbeatInfo *, const char*, const char*);

#define soap_new___ns2__uploadCMAHeartbeatInfo(soap, n) soap_instantiate___ns2__uploadCMAHeartbeatInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__uploadCMAHeartbeatInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__uploadCMAHeartbeatInfo * SOAP_FMAC2 soap_instantiate___ns2__uploadCMAHeartbeatInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__uploadCMAHeartbeatInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__uploadCMAData
#define SOAP_TYPE___ns2__uploadCMAData (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__uploadCMAData(struct soap*, struct __ns2__uploadCMAData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__uploadCMAData(struct soap*, const struct __ns2__uploadCMAData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__uploadCMAData(struct soap*, const char*, int, const struct __ns2__uploadCMAData *, const char*);
SOAP_FMAC3 struct __ns2__uploadCMAData * SOAP_FMAC4 soap_in___ns2__uploadCMAData(struct soap*, const char*, struct __ns2__uploadCMAData *, const char*);

#ifndef soap_write___ns2__uploadCMAData
#define soap_write___ns2__uploadCMAData(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__uploadCMAData(soap, data), 0) || soap_put___ns2__uploadCMAData(soap, data, "-ns2:uploadCMAData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__uploadCMAData(struct soap*, const struct __ns2__uploadCMAData *, const char*, const char*);

#ifndef soap_read___ns2__uploadCMAData
#define soap_read___ns2__uploadCMAData(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__uploadCMAData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__uploadCMAData * SOAP_FMAC4 soap_get___ns2__uploadCMAData(struct soap*, struct __ns2__uploadCMAData *, const char*, const char*);

#define soap_new___ns2__uploadCMAData(soap, n) soap_instantiate___ns2__uploadCMAData(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__uploadCMAData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__uploadCMAData * SOAP_FMAC2 soap_instantiate___ns2__uploadCMAData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__uploadCMAData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__upLoadCACDataResponse
#define SOAP_TYPE_PointerTo_ns1__upLoadCACDataResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__upLoadCACDataResponse(struct soap*, const char *, int, _ns1__upLoadCACDataResponse *const*, const char *);
SOAP_FMAC3 _ns1__upLoadCACDataResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__upLoadCACDataResponse(struct soap*, const char*, _ns1__upLoadCACDataResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__upLoadCACDataResponse
#define soap_write_PointerTo_ns1__upLoadCACDataResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__upLoadCACDataResponse(soap, data), 0) || soap_put_PointerTo_ns1__upLoadCACDataResponse(soap, data, "ns1:upLoadCACDataResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__upLoadCACDataResponse
#define soap_read_PointerTo_ns1__upLoadCACDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__upLoadCACDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__upLoadCACDataResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__upLoadCACDataResponse(struct soap*, _ns1__upLoadCACDataResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__upLoadCACData
#define SOAP_TYPE_PointerTo_ns1__upLoadCACData (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__upLoadCACData(struct soap*, const char *, int, _ns1__upLoadCACData *const*, const char *);
SOAP_FMAC3 _ns1__upLoadCACData ** SOAP_FMAC4 soap_in_PointerTo_ns1__upLoadCACData(struct soap*, const char*, _ns1__upLoadCACData **, const char*);

#ifndef soap_write_PointerTo_ns1__upLoadCACData
#define soap_write_PointerTo_ns1__upLoadCACData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__upLoadCACData(soap, data), 0) || soap_put_PointerTo_ns1__upLoadCACData(soap, data, "ns1:upLoadCACData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__upLoadCACData
#define soap_read_PointerTo_ns1__upLoadCACData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__upLoadCACData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__upLoadCACData ** SOAP_FMAC4 soap_get_PointerTo_ns1__upLoadCACData(struct soap*, _ns1__upLoadCACData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__uploadCMAHeartbeatInfoResponse
#define SOAP_TYPE_PointerTo_ns1__uploadCMAHeartbeatInfoResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(struct soap*, const char *, int, _ns1__uploadCMAHeartbeatInfoResponse *const*, const char *);
SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(struct soap*, const char*, _ns1__uploadCMAHeartbeatInfoResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCMAHeartbeatInfoResponse
#define soap_write_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(soap, data), 0) || soap_put_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(soap, data, "ns1:uploadCMAHeartbeatInfoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCMAHeartbeatInfoResponse
#define soap_read_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCMAHeartbeatInfoResponse(struct soap*, _ns1__uploadCMAHeartbeatInfoResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__uploadCMAHeartbeatInfo
#define SOAP_TYPE_PointerTo_ns1__uploadCMAHeartbeatInfo (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCMAHeartbeatInfo(struct soap*, const char *, int, _ns1__uploadCMAHeartbeatInfo *const*, const char *);
SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfo ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCMAHeartbeatInfo(struct soap*, const char*, _ns1__uploadCMAHeartbeatInfo **, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCMAHeartbeatInfo
#define soap_write_PointerTo_ns1__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__uploadCMAHeartbeatInfo(soap, data), 0) || soap_put_PointerTo_ns1__uploadCMAHeartbeatInfo(soap, data, "ns1:uploadCMAHeartbeatInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCMAHeartbeatInfo
#define soap_read_PointerTo_ns1__uploadCMAHeartbeatInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCMAHeartbeatInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAHeartbeatInfo ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCMAHeartbeatInfo(struct soap*, _ns1__uploadCMAHeartbeatInfo **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__uploadCMADataResponse
#define SOAP_TYPE_PointerTo_ns1__uploadCMADataResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCMADataResponse(struct soap*, const char *, int, _ns1__uploadCMADataResponse *const*, const char *);
SOAP_FMAC3 _ns1__uploadCMADataResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCMADataResponse(struct soap*, const char*, _ns1__uploadCMADataResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCMADataResponse
#define soap_write_PointerTo_ns1__uploadCMADataResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__uploadCMADataResponse(soap, data), 0) || soap_put_PointerTo_ns1__uploadCMADataResponse(soap, data, "ns1:uploadCMADataResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCMADataResponse
#define soap_read_PointerTo_ns1__uploadCMADataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCMADataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMADataResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCMADataResponse(struct soap*, _ns1__uploadCMADataResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__uploadCMAData
#define SOAP_TYPE_PointerTo_ns1__uploadCMAData (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__uploadCMAData(struct soap*, const char *, int, _ns1__uploadCMAData *const*, const char *);
SOAP_FMAC3 _ns1__uploadCMAData ** SOAP_FMAC4 soap_in_PointerTo_ns1__uploadCMAData(struct soap*, const char*, _ns1__uploadCMAData **, const char*);

#ifndef soap_write_PointerTo_ns1__uploadCMAData
#define soap_write_PointerTo_ns1__uploadCMAData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__uploadCMAData(soap, data), 0) || soap_put_PointerTo_ns1__uploadCMAData(soap, data, "ns1:uploadCMAData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__uploadCMAData
#define soap_read_PointerTo_ns1__uploadCMAData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__uploadCMAData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__uploadCMAData ** SOAP_FMAC4 soap_get_PointerTo_ns1__uploadCMAData(struct soap*, _ns1__uploadCMAData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data), 0) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
