/* soapCAGWebServicePortSoapService.cpp
   Generated by gSOAP 2.8.4 from CAGAccessService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapCAGWebServicePortSoapService.h"

CAGWebServicePortSoapService::CAGWebServicePortSoapService()
{	CAGWebServicePortSoapService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

CAGWebServicePortSoapService::CAGWebServicePortSoapService(const struct soap &_soap) : soap(_soap)
{ }

CAGWebServicePortSoapService::CAGWebServicePortSoapService(soap_mode iomode)
{	CAGWebServicePortSoapService_init(iomode, iomode);
}

CAGWebServicePortSoapService::CAGWebServicePortSoapService(soap_mode imode, soap_mode omode)
{	CAGWebServicePortSoapService_init(imode, omode);
}

CAGWebServicePortSoapService::~CAGWebServicePortSoapService()
{ }

void CAGWebServicePortSoapService::CAGWebServicePortSoapService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://tempuri.org/CAGWebServicePortSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns3", "http://tempuri.org/CAGWebServicePortSoap12", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void CAGWebServicePortSoapService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

#ifndef WITH_PURE_VIRTUAL
CAGWebServicePortSoapService *CAGWebServicePortSoapService::copy()
{	CAGWebServicePortSoapService *dup = SOAP_NEW_COPY(CAGWebServicePortSoapService(*(struct soap*)this));
	return dup;
}
#endif

int CAGWebServicePortSoapService::soap_close_socket()
{	return soap_closesock(this);
}

int CAGWebServicePortSoapService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int CAGWebServicePortSoapService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int CAGWebServicePortSoapService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int CAGWebServicePortSoapService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int CAGWebServicePortSoapService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void CAGWebServicePortSoapService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void CAGWebServicePortSoapService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *CAGWebServicePortSoapService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void CAGWebServicePortSoapService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *CAGWebServicePortSoapService::soap_header()
{	return this->header;
}

int CAGWebServicePortSoapService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->error;
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET CAGWebServicePortSoapService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET CAGWebServicePortSoapService::accept()
{	return soap_accept(this);
}

int CAGWebServicePortSoapService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ns2__uploadCMAData(CAGWebServicePortSoapService*);
static int serve___ns2__uploadCMAHeartbeatInfo(CAGWebServicePortSoapService*);
static int serve___ns2__upLoadCACData(CAGWebServicePortSoapService*);

int CAGWebServicePortSoapService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:uploadCMAData"))
		return serve___ns2__uploadCMAData(this);
	if (!soap_match_tag(this, this->tag, "ns1:uploadCMAHeartbeatInfo"))
		return serve___ns2__uploadCMAHeartbeatInfo(this);
	if (!soap_match_tag(this, this->tag, "ns1:upLoadCACData"))
		return serve___ns2__upLoadCACData(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve___ns2__uploadCMAData(CAGWebServicePortSoapService *soap)
{	struct __ns2__uploadCMAData soap_tmp___ns2__uploadCMAData;
	_ns1__uploadCMADataResponse ns1__uploadCMADataResponse;
	ns1__uploadCMADataResponse.soap_default(soap);
	soap_default___ns2__uploadCMAData(soap, &soap_tmp___ns2__uploadCMAData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns2__uploadCMAData(soap, &soap_tmp___ns2__uploadCMAData, "-ns2:uploadCMAData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->uploadCMAData(soap_tmp___ns2__uploadCMAData.ns1__uploadCMAData, &ns1__uploadCMADataResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__uploadCMADataResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__uploadCMADataResponse.soap_put(soap, "ns1:uploadCMADataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__uploadCMADataResponse.soap_put(soap, "ns1:uploadCMADataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns2__uploadCMAHeartbeatInfo(CAGWebServicePortSoapService *soap)
{	struct __ns2__uploadCMAHeartbeatInfo soap_tmp___ns2__uploadCMAHeartbeatInfo;
	_ns1__uploadCMAHeartbeatInfoResponse ns1__uploadCMAHeartbeatInfoResponse;
	ns1__uploadCMAHeartbeatInfoResponse.soap_default(soap);
	soap_default___ns2__uploadCMAHeartbeatInfo(soap, &soap_tmp___ns2__uploadCMAHeartbeatInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns2__uploadCMAHeartbeatInfo(soap, &soap_tmp___ns2__uploadCMAHeartbeatInfo, "-ns2:uploadCMAHeartbeatInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->uploadCMAHeartbeatInfo(soap_tmp___ns2__uploadCMAHeartbeatInfo.ns1__uploadCMAHeartbeatInfo, &ns1__uploadCMAHeartbeatInfoResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__uploadCMAHeartbeatInfoResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__uploadCMAHeartbeatInfoResponse.soap_put(soap, "ns1:uploadCMAHeartbeatInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__uploadCMAHeartbeatInfoResponse.soap_put(soap, "ns1:uploadCMAHeartbeatInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns2__upLoadCACData(CAGWebServicePortSoapService *soap)
{	struct __ns2__upLoadCACData soap_tmp___ns2__upLoadCACData;
	_ns1__upLoadCACDataResponse ns1__upLoadCACDataResponse;
	ns1__upLoadCACDataResponse.soap_default(soap);
	soap_default___ns2__upLoadCACData(soap, &soap_tmp___ns2__upLoadCACData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns2__upLoadCACData(soap, &soap_tmp___ns2__upLoadCACData, "-ns2:upLoadCACData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->upLoadCACData(soap_tmp___ns2__upLoadCACData.ns1__upLoadCACData, &ns1__upLoadCACDataResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__upLoadCACDataResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__upLoadCACDataResponse.soap_put(soap, "ns1:upLoadCACDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__upLoadCACDataResponse.soap_put(soap, "ns1:upLoadCACDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
